using Xunit;

namespace NgocTrangHouseManagementSystem.EntityFrameworkCore;

[CollectionDefinition(NgocTrangHouseManagementSystemTestConsts.CollectionDefinitionName)]
public class NgocTrangHouseManagementSystemEntityFrameworkCoreCollection : ICollectionFixture<NgocTrangHouseManagementSystemEntityFrameworkCoreFixture>
{

}
