using Volo.Abp;

namespace NgocTrangHouseManagementSystem.EntityFrameworkCore;

public abstract class NgocTrangHouseManagementSystemEntityFrameworkCoreTestBase : NgocTrangHouseManagementSystemTestBase<NgocTrangHouseManagementSystemEntityFrameworkCoreTestModule>
{

}
