using NgocTrangHouseManagementSystem.EntityFrameworkCore;
using Xunit;

namespace NgocTrangHouseManagementSystem.EntityFrameworkCore;

public class NgocTrangHouseManagementSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<NgocTrangHouseManagementSystemEntityFrameworkCoreFixture>
{

}
