<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>BuildingManagement</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Abp" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.Ddd.Domain.Shared" Version="10.6.1" />
    <PackageReference Include="Volo.Abp.Validation" Version="10.6.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\BuildingManagement\*.json" />
    <Content Remove="Localization\BuildingManagement\*.json" />
  </ItemGroup>

</Project>
