<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>BuildingManagement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingManagement.Domain\BuildingManagement.Domain.csproj" />
    <ProjectReference Include="..\BuildingManagement.TestBase\BuildingManagement.TestBase.csproj" />
  </ItemGroup>


</Project>
